 --- !Ups
CREATE TABLE USERS
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	USER_NAME VARCHAR(100),
	HASHED_PASSWORD VARCHAR(100),
	SALT VARCHAR(100)
);


CREATE INDEX USER_NAME_IDX ON USERS(USER_NAME);


# --- !Downs
DROP TABLE USERS;