# --- !Ups
CREATE TABLE USERS
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	USER_NAME VARCHAR(100),
	HASHED_PASSWORD VARCHAR(250)
);

CREATE TABLE ALBUMS
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(999999)
);

CREATE TABLE PHOTOS
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	UUID VARCHAR(36) NOT NULL,
	ALBUM_UUID VARCHAR(36),
	IMAGE BLOB
);

CREATE INDEX USER_NAME_IDX ON USERS(USER_NAME);
CREATE INDEX UUID_IDX ON ALBUMS(UUID);
CREATE INDEX ALBUM_UUID_IDX ON PHOTOS(ALBUM_UUID);

# --- !Downs
DROP TABLE USERS;